version: '3.5'

 

services:

  # dd-agent-dogfood-jmx:

  #   container_name: dd-java-agent

  #   image: sathyamurthyr/dd-java-agent:1.0

  #   environment:

  #     - DD_HOSTNAME=datadog

  #     - DD_API_KEY=63fb02a9319efd1df1bb76f91f35f36c

  #     - DD_APM_ENABLED=true

  #     - DD_APM_NON_LOCAL_TRAFFIC=true

  #     - DD_PROCESS_AGENT_ENABLED=true

  #     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true"

  #     - DD_LOG_LEVEL=debug

  #     - DD_LOGS_ENABLED=true

  #     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true

  #     - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"

  #     - SD_JMX_ENABLE=true

  #   ports:

  #    - "8124:8125"

  #    - "8123:8126"

  #   volumes:

  #     - /proc/:/host/proc/:ro

  #     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  #   networks:

  #     - app

 

  springfront:

    build:

      context: .

      dockerfile: Dockerfiles/Dockerfile.springfront

    container_name: springfront

    image: sathyamurthyr/springfront-image:1.0

    environment:

      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS_COMMON}

      - URL=http://springback:8088

    hostname: springfront

    ports:

      - "8081:8080"

    volumes:

      - /dd-java-agent.jar:/springblog-main/dd-java-agent.jar

    networks:

      - app

 

  springback:

    build:

      context: .

      dockerfile: Dockerfiles/Dockerfile.springback

    container_name: springback

    image: sathyamurthyr/springback-image:1.0

    environment:

      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS_COMMON}

    hostname: springback

    ports:

      - "8085:8088"

    volumes:

      - /dd-java-agent.jar:/springblog-main/dd-java-agent.jar

    networks:

      - app

 

networks:

  app:

    external: false

    driver: bridge

    name: app

 

# Define the common environment variable section

x-common-environment:

  environment:

    - JAVA_TOOL_OPTIONS_COMMON=-javaagent:/springblog-main/dd-java-agent.jar -Ddd.agent.host=dd-agent-dogfood-jmx -Ddd.env=dev -Ddd.version=12 -Ddd.trace.sample.rate=1 -Ddd.logs.injection=true -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.tags=env:dev

 